{
 "title": "Custom Exporter Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(custom_student_metric,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(custom_student_metric,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "95-й перцентиль за 5 минут",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95, custom_student_metric{job=\"$job\", instance=\"$instance\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Медиана за 5 минут",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "quantile_over_time(0.5, custom_student_metric{job=\"$job\", instance=\"$instance\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Относительная динамика",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "custom_student_metric{job=\"$job\", instance=\"$instance\"} \r\n- \r\ncustom_student_metric{job=\"$job\", instance=\"$instance\"} offset 1m\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сколько раз было >80 за 5 минут",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time((custom_student_metric{job=\"$job\", instance=\"$instance\"} > bool 80)[5m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сумма по instance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (instance) (custom_student_metric{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее по job (текущее)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg by (job) (custom_student_metric)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее по всем инстансам",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(custom_student_metric{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Темп изменения (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(custom_student_metric{job=\"$job\", instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Максимум за 5 минут",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(custom_student_metric{job=\"$job\", instance=\"$instance\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Минимум за 5 минут",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(custom_student_metric{job=\"$job\", instance=\"$instance\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее за 5 минут",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avg_over_time(custom_student_metric{job=\"$job\", instance=\"$instance\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Student KPI (текущее значение)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "custom_student_metric{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}